import type { Phrase } from '@/types/phrase'

const part2: Phrase[] = [
  {
    word: 'KPI (Key Performance Indicator)',
    english_definition:
      'A measurable value that demonstrates how effectively a company is achieving key business objectives.',
    persian_meaning: 'شاخص کلیدی عملکرد',
    example: 'Our primary KPI for this quarter is customer retention.',
    category: 'Metrics, Management',
    abbreviation: 'KPI',
    related_terms: 'Metric, Goal, Objective',
    notes: 'معیاری برای سنجش موفقیت در دستیابی به اهداف.',
  },
  {
    word: 'Revenue',
    english_definition:
      'The total income generated by the sale of goods or services related to the company’s primary operations.',
    persian_meaning: 'درآمد / عایدی',
    example:
      'The company reported a 15% increase in revenue year-over-year.',
    category: 'Finance, Metrics',
    related_terms: 'Sales, Income, Turnover',
    notes: 'کل مبلغی که از فروش کالا یا خدمات حاصل میشود.',
  },
  {
    word: 'Profit Margin',
    english_definition:
      'The percentage of revenue that remains after all expenses and costs have been deducted.',
    persian_meaning: 'حاشیه سود / سود خالص',
    example: 'High operational costs reduced our profit margin.',
    category: 'Finance, Metrics',
    related_terms: 'Profit, Margin, Net Income',
    notes: 'نشان میدهد چه درصدی از فروش به سود تبدیل شده است.',
  },
  {
    word: 'ROI (Return on Investment)',
    english_definition:
      'A performance measure used to evaluate the efficiency or profitability of an investment.',
    persian_meaning: 'نرخ بازگشت سرمایه',
    example:
      'The marketing campaign had a strong ROI, generating more in sales than it cost.',
    category: 'Finance, Metrics',
    abbreviation: 'ROI',
    related_terms: 'Investment, Profitability, Performance',
    notes: 'سود حاصل از سرمایهگذاری نسبت به هزینه آن.',
  },
  {
    word: 'Sales Target / Quota',
    english_definition:
      'A specific sales goal that an individual, team, or company is expected to achieve within a certain period.',
    persian_meaning: 'هدف فروش / سهمیه فروش',
    example: 'The sales team exceeded their quota for the third consecutive quarter.',
    category: 'Sales, Management',
    related_terms: 'Goal, Objective, Performance',
    notes: 'میزان فروشی که باید در یک دوره زمانی مشخص انجام شود.',
  },
  {
    word: 'Sales Forecast',
    english_definition:
      'An estimate of future sales revenue based on historical data and market trends.',
    persian_meaning: 'پیشبینی فروش',
    example: 'The sales forecast helps with inventory planning and resource allocation.',
    category: 'Sales, Planning',
    related_terms: 'Prediction, Projection, Outlook',
    notes: 'تخمین میزان فروش در آینده.',
  },
  {
    word: 'Average Deal Size',
    english_definition:
      'The average monetary value of each completed sale or transaction.',
    persian_meaning: 'میانگین ارزش هر معامله',
    example: 'We aim to increase our average deal size by offering premium packages.',
    category: 'Sales Metrics, Finance',
    related_terms: 'Deal Value, Revenue, Average Sale Price',
    notes: 'متوسط مبلغی که از هر فروش به دست میآید.',
  },
  {
    word: 'Customer Acquisition Cost (CAC)',
    english_definition:
      'The total cost spent on acquiring new customers divided by the number of new customers acquired during that period.',
    persian_meaning: 'هزینه جذب مشتری',
    example: 'High CAC suggests our marketing channels are inefficient.',
    category: 'Finance, Metrics, Marketing',
    abbreviation: 'CAC',
    related_terms: 'Acquisition, Cost, Marketing Spend',
    notes: 'هزینه لازم برای به دست آوردن یک مشتری جدید.',
  },
  {
    word: 'Lifetime Value (LTV)',
    english_definition:
      'The total predicted revenue a business can expect from a single customer account throughout their relationship.',
    persian_meaning: 'ارزش طول عمر مشتری',
    example: 'A high LTV indicates strong customer loyalty and retention.',
    category: 'Metrics, CRM, Finance',
    abbreviation: 'LTV',
    related_terms: 'Customer Value, Retention, Loyalty',
    notes:
      'پیشبینی کل درآمدی که یک مشتری در طول دوره همکاری با شرکت ایجاد میکند.',
  },
  {
    word: 'Growth Rate',
    english_definition:
      'The percentage change in a specific metric (like revenue or customer base) over a given period.',
    persian_meaning: 'نرخ رشد',
    example: 'The company achieved a 20% annual growth rate in its user base.',
    category: 'Metrics, Finance',
    related_terms: 'Percentage Increase, Expansion, Scalability',
    notes: 'سرعت افزایش یک شاخص در طول زمان.',
  },
  {
    word: 'Win Rate',
    english_definition:
      'The percentage of deals or opportunities that are successfully closed as won.',
    persian_meaning: 'نرخ موفقیت در بستن قراردادها',
    example: 'Improving sales training can significantly increase the win rate.',
    category: 'Sales Metrics, CRM',
    related_terms: 'Conversion Rate, Close Rate, Success Rate',
    notes: 'نشاندهنده میزان موفقیت تیم فروش در تبدیل فرصتها به مشتری.',
  },
  {
    word: 'Gross Sales',
    english_definition:
      'The total sales revenue reported before any deductions or adjustments.',
    persian_meaning: 'فروش ناخالص',
    example: 'Gross sales were up, but net sales remained flat after returns.',
    category: 'Finance, Sales',
    related_terms: 'Total Sales, Revenue',
    notes: 'مجموع کل فروش قبل از کسر بازگشت کالا یا تخفیفها.',
  },
  {
    word: 'Net Sales',
    english_definition:
      'Gross sales minus returns, allowances, and discounts.',
    persian_meaning: 'فروش خالص',
    example: 'Net sales provide a more accurate picture of actual revenue.',
    category: 'Finance, Sales',
    related_terms: 'Revenue, Gross Sales, Deductions',
    notes: 'فروش واقعی پس از کسر موارد مربوطه از فروش ناخالص.',
  },
  {
    word: 'Volume',
    english_definition:
      'The quantity or number of units sold during a specific period.',
    persian_meaning: 'حجم فروش / تعداد فروش',
    example: 'We aim to increase sales volume by 10% next quarter.',
    category: 'Sales, Metrics',
    related_terms: 'Quantity, Units Sold, Sales Figures',
    notes: 'تعداد واحدهای فروخته شده.',
  },
  {
    word: 'Break-even Point',
    english_definition:
      'The point at which total cost and total revenue are equal, meaning no profit or loss is incurred.',
    persian_meaning: 'نقطه سربهسر',
    example: 'The product needs to sell 500 units to reach its break-even point.',
    category: 'Finance, Business',
    related_terms: 'Cost, Revenue, Profitability',
    notes: 'نقطهای که در آن هزینه و درآمد برابر میشوند.',
  },
  {
    word: 'Sales Strategy',
    english_definition:
      'A long-term plan outlining how a business will reach its target customers and achieve a competitive advantage.',
    persian_meaning: 'استراتژی فروش',
    example: 'Our new sales strategy focuses on penetrating emerging markets.',
    category: 'Sales, Management',
    related_terms: 'Plan, Approach, Go-to-Market',
    notes: 'رویکرد کلی برای رسیدن به اهداف فروش.',
  },
  {
    word: 'Territory Management',
    english_definition:
      'The process of assigning specific geographic areas or customer groups to sales representatives.',
    persian_meaning: 'مدیریت مناطق جغرافیایی / مدیریت سهم بازار',
    example:
      'Effective territory management ensures balanced workloads and market coverage.',
    category: 'Sales, Management',
    related_terms: 'Sales Territory, Assignment, Coverage',
    notes: 'تقسیمبندی بازار یا مشتریان بین اعضای تیم فروش.',
  },
  {
    word: 'Sales Enablement',
    english_definition:
      'Providing the sales team with the resources, content, training, and tools they need to be effective.',
    persian_meaning: 'توانمندسازی فروش',
    example:
      'Sales enablement initiatives include better onboarding and updated sales collateral.',
    category: 'Sales, Management, Training',
    related_terms: 'Resources, Training, Content, Tools',
    notes: 'فراهم کردن ابزار و دانش الزم برای موفقیت تیم فروش.',
  },
  {
    word: 'Business to Business (B2B)',
    english_definition:
      'Transactions between companies, rather than between companies and individual consumers.',
    persian_meaning: 'فروش به کسبوکارها',
    abbreviation: 'B2B',
    example: 'Our main market is B2B, selling software solutions to other companies.',
    category: 'Sales, Business Models',
    related_terms: 'Enterprise Sales, Wholesale',
    notes: 'مدلی که در آن محصولات یا خدمات به شرکتهای دیگر فروخته میشوند.',
  },
  {
    word: 'Business to Consumer (B2C)',
    english_definition:
      'Transactions between a company and individual consumers who are the end-users.',
    persian_meaning: 'فروش به مصرفکننده نهایی',
    abbreviation: 'B2C',
    example: 'Retail stores and online shops typically operate on a B2C model.',
    category: 'Sales, Business Models',
    related_terms: 'Retail, E-commerce, Consumer Market',
    notes: 'مدلی که در آن محصولات یا خدمات مستقیماً به مصرفکنندگان فروخته میشوند.',
  },
  {
    word: 'Direct Sales',
    english_definition:
      'Selling products or services directly to consumers, bypassing intermediaries like retailers or wholesalers.',
    persian_meaning: 'فروش مستقیم',
    example:
      'Direct sales channels include our website and our own retail stores.',
    category: 'Sales, Channels',
    related_terms: 'In-person Sales, E-commerce, Manufacturer-direct',
    notes: 'فروش بدون واسطه به مشتری نهایی.',
  },
  {
    word: 'Inbound Sales',
    english_definition:
      'A sales approach where potential customers initiate contact due to interest in marketing content or solutions.',
    persian_meaning: 'فروش جذبکننده / مشتری خودش میآید',
    example:
      'Inbound sales teams focus on understanding the needs of leads who have already shown interest.',
    category: 'Sales, Methodology',
    related_terms: 'Lead Generation, Content Marketing, Pull Strategy',
    notes:
      'تمرکز بر مشتریانی که خودشان از طریق محتوا یا بازاریابی با شرکت ارتباط برقرار کردهاند.',
  },
  {
    word: 'Outbound Sales',
    english_definition:
      'A sales approach where the sales team initiates contact with potential customers (e.g., cold calling, direct outreach).',
    persian_meaning: 'فروش برونگرا / تماس مستقیم با مشتری',
    example:
      'Outbound sales often involve cold calls and targeted email campaigns.',
    category: 'Sales, Methodology',
    related_terms: 'Cold Calling, Prospecting, Push Strategy',
    notes: 'تیمی که فعاالنه با مشتریان بالقوه تماس میگیرد.',
  },
  {
    word: 'Cold Calling',
    english_definition:
      'Contacting potential customers who have not previously expressed interest in the offered product or service.',
    persian_meaning: 'تماس سرد / تماس با مشتری بدون شناخت قبلی',
    example:
      'Cold calling is a challenging but sometimes effective outbound sales tactic.',
    category: 'Sales, Tactics',
    related_terms: 'Outbound, Prospecting, Unsolicited Call',
    notes: 'تماس تلفنی با افرادی که شناختی از محصول یا خدمات ندارند.',
  },
  {
    word: 'Account Management',
    english_definition:
      'The process of managing relationships with existing clients to ensure satisfaction, retention, and potential growth.',
    persian_meaning: 'مدیریت حسابهای مشتریان',
    example:
      'Dedicated account managers help build strong, long-term client relationships.',
    category: 'CRM, Sales',
    related_terms: 'Client Relations, Customer Success, Retention',
    notes: 'مدیریت و توسعه روابط با مشتریان فعلی',
  },
  {
    word: 'Software as a Service (SaaS)',
    english_definition:
      'A software distribution model where a third-party provider hosts applications and makes them available to customers over the Internet.',
    persian_meaning: 'نرمافزار به عنوان سرویس',
    example: 'Many CRM systems are now cloud-based SaaS products.',
    category: 'Technology, Business Models',
    abbreviation: 'SaaS',
    related_terms: 'Cloud Computing, Subscription, Hosted Software',
    notes:
      'مدلی که در آن نرمافزار به جای نصب روی دستگاه کاربر، از طریق اینترنت در دسترس است.',
  },
  {
    word: 'Dashboard',
    english_definition:
      'A visual display of the most important information needed to achieve one or more objectives; consolidated and arranged on a single screen.',
    persian_meaning: 'داشبورد مدیریتی / نمایش وضعیت',
    example: 'The sales dashboard shows real-time performance metrics and trends.',
    category: 'Technology, Analytics, Management',
    related_terms: 'Visualization, Reporting, UI',
    notes:
      'صفحه نمایش گرافیکی که اطلاعات کلیدی را به صورت یکجا نشان میدهد.',
  },
  {
    word: 'Lead Scoring',
    english_definition:
      'A methodology used to rank prospects according to a value attached to them by the sales or marketing department.',
    persian_meaning: 'امتیازدهی به سرنخها',
    example: 'Lead scoring helps prioritize sales efforts on the most promising leads.',
    category: 'CRM, Marketing, Sales',
    related_terms: 'Prospect Ranking, Qualification, CRM',
    notes:
      'سیستمی برای ارزیابی و اولویتبندی سرنخها بر اساس احتمال تبدیل شدنشان به مشتری.',
  },
  {
    word: 'Cloud-based CRM',
    english_definition:
      'A Customer Relationship Management system that is hosted on the provider\'s servers and accessed via the internet.',
    persian_meaning: 'سیستم مدیریت مشتری مبتنی بر ابر',
    example: 'Cloud-based CRM offers flexibility and scalability for businesses of all sizes.',
    category: 'Technology, CRM',
    related_terms: 'SaaS, Hosted CRM, Online CRM',
    notes:
      'سیستم CRM که روی سرورهای ارائهدهنده میزبانی شده و از طریق اینترنت قابل دسترسی است.',
  },
  {
    word: 'Analytics',
    english_definition:
      'The systematic computational analysis of data or statistics.',
    persian_meaning: 'تجزیه و تحلیل دادهها',
    example: 'Sales analytics helps us understand customer behavior and market trends.',
    category: 'Technology, Data, Business Intelligence',
    related_terms: 'Data Analysis, Reporting, Insights, BI',
    notes:
      'فرآیند بررسی دادهها برای یافتن الگوها، روندها و کسب بینش.',
  },
  {
    word: 'Opportunity',
    english_definition:
      'A qualified prospect that has a need, budget, and timeframe for making a purchase.',
    persian_meaning: 'فرصت فروش',
    example: 'We identified three major opportunities in the healthcare sector this month.',
    category: 'Sales, CRM',
    abbreviation: 'Opp',
    related_terms: 'Prospect, Deal, Pipeline',
    notes: 'یک سرنخ واجد شرایط که احتمال تبدیل به معامله دارد.',
  },
  {
    word: 'Customer Retention',
    english_definition:
      'The ability of a company to retain its customers over a specific period.',
    persian_meaning: 'حفظ مشتری',
    example: 'Improving customer service is key to improving customer retention.',
    category: 'CRM, Metrics',
    related_terms: 'Loyalty, Churn, Satisfaction',
    notes: 'استراتژیها و فعالیتهای حفظ مشتریان موجود.',
  },
  {
    word: 'Churn Rate',
    english_definition:
      'The percentage of customers who stop using a company\'s product or service during a given time period.',
    persian_meaning: 'نرخ ریزش مشتریان',
    example:
      'Reducing churn rate is more cost-effective than acquiring new customers.',
    category: 'CRM, Metrics',
    related_terms: 'Attrition, Turnover, Retention Rate',
    notes: 'معیار اندازهگیری میزان از دست دادن مشتریان.',
  },
  {
    word: 'Lead Nurturing',
    english_definition:
      'The process of developing relationships with buyers at every stage of the sales funnel.',
    persian_meaning: 'پرورش سرنخها',
    example:
      'Automated email sequences are a common lead nurturing technique.',
    category: 'Marketing, CRM, Sales',
    related_terms: 'Engagement, Follow-up, Relationship Building',
    notes: 'فرآیند ارتباط مداوم با سرنخها برای آماده کردن آنان برای خرید.',
  },
  {
    word: 'Pipeline',
    english_definition:
      'A visual representation of where prospects are in the sales process, from initial contact to closed deal.',
    persian_meaning: 'قیف فروش / خط لوله فروش',
    example:
      'Our sales pipeline is strong, with many opportunities in the negotiation stage.',
    category: 'Sales, CRM',
    related_terms: 'Funnel, Stages, Prospects',
    notes: 'نمای کلی از تمام فرصتهای فروش در مراحل مختلف فرآیند فروش.',
  },
  {
    word: 'Conversion Rate',
    english_definition:
      'The percentage of visitors or leads who take a desired action (e.g., make a purchase, sign up).',
    persian_meaning: 'نرخ تبدیل',
    example: 'The website\'s conversion rate improved after the redesign.',
    category: 'Sales, Marketing, Metrics',
    related_terms: 'Win Rate, Funnel, Effectiveness',
    notes: 'نسبت افرادی که یک عمل هدفمند را انجام میدهند.',
  },
  {
    word: 'Objection Handling',
    english_definition:
      'The way a salesperson addresses and resolves a potential customer\'s concerns or hesitations.',
    persian_meaning: 'مدیریت اعتراضات مشتری',
    example:
      'Good objection handling can turn a hesitant prospect into a buyer.',
    category: 'Sales, Skills',
    related_terms: 'Negotiation, Rebuttal, Concerns',
    notes: 'مهارت پاسخ دادن به نگرانیها و موانع ذهنی مشتری.',
  },
  {
    word: 'Value Proposition',
    english_definition:
      'A clear statement that explains how a product solves a customer\'s problem, delivers specific benefits, and why it\'s better than the competition.',
    persian_meaning: 'گزاره ارزش / ارزش پیشنهادی',
    example:
      'Our core value proposition is saving customers at least 20 hours per month on administrative tasks.',
    category: 'Marketing, Sales, Strategy',
    related_terms: 'USP (Unique Selling Proposition), Benefit, Differentiation',
    notes: 'بیان واضح از ارزش منحصر به فرد ارائه شده به مشتری.',
  },
  {
    word: 'Up-selling / Cross-selling',
    english_definition:
      'Up-selling: Encouraging a customer to buy a more expensive version of the product. Cross-selling: Suggesting related or complementary products.',
    persian_meaning: 'فروش افزوده / فروش متقابل',
    example:
      'After purchasing a laptop, we cross-sell a laptop bag and up-sell to a model with more memory.',
    category: 'Sales, Tactics',
    related_terms: 'Add-on Sale, Revenue Growth, Recommendation',
    notes: 'تکنیکهای افزایش ارزش معامله با فروش محصولات مرتبط یا گرانتر.',
  },
  {
    word: 'Key Account',
    english_definition:
      'A customer that provides a significant portion of a company\'s revenue or has strategic importance.',
    persian_meaning: 'حساب کلیدی',
    example:
      'We have dedicated key account managers for our top five clients.',
    category: 'Sales, CRM',
    related_terms: 'Major Client, Strategic Account, VIP Customer',
    notes: 'مشتری بسیار مهم و باارزش که نیازمند توجه و مدیریت ویژه است.',
  },
  {
    word: 'Customer Relationship Management (CRM)',
    english_definition:
      'A technology for managing all your company\'s relationships and interactions with current and potential customers.',
    persian_meaning: 'مدیریت ارتباط با مشتری',
    example:
      'We use a CRM to track all customer communications and sales activities.',
    category: 'Technology, CRM, Strategy',
    abbreviation: 'CRM',
    related_terms: 'Software, Customer Data, Relationship',
    notes: 'استراتژی و ابزار مدیریت کلیه تعامالت با مشتریان برای بهبود روابط.',
  },
  {
    word: 'Sales Floor',
    english_definition:
      'The area where sales representatives work, often used in retail or call centers. Also refers to the sales team collectively.',
    persian_meaning: 'سالن فروش / نیروی فروش',
    example:
      'The sales floor was buzzing with activity during the holiday season.',
    category: 'Sales, Environment',
    related_terms: 'Retail Space, Call Center, Team',
    notes: 'فضای فیزیکی یا تیمی که عملیات فروش در آن انجام میشود.',
  },
  {
    word: 'Sales Cycle',
    english_definition:
      'The series of steps a company takes to move a prospect from initial awareness to a completed sale.',
    persian_meaning: 'چرخه فروش',
    example: 'Our average sales cycle for enterprise deals is six months.',
    category: 'Sales, Process',
    related_terms: 'Process, Stages, Timeline',
    notes: 'فرآیند کامل از شناسایی مشتری تا دریافت وجه.',
  },
  {
    word: 'Sales Collateral',
    english_definition:
      'The collection of materials used to support the sales process (e.g., brochures, case studies, presentations).',
    persian_meaning: 'ابزار و مدارک پشتیبان فروش',
    example:
      'Updated sales collateral helped the team communicate the product\'s value more effectively.',
    category: 'Sales, Marketing',
    related_terms: 'Marketing Materials, Brochures, Case Studies',
    notes: 'محتوا و اسنادی که فروشنده برای متقاعد کردن مشتری استفاده میکند.',
  },
  {
    word: 'Sales Force Automation (SFA)',
    english_definition:
      'Software that automates routine sales tasks such as contact management, lead tracking, and forecasting.',
    persian_meaning: 'اتوماسیون نیروی فروش',
    example:
      'SFA tools help reps spend less time on admin and more time selling.',
    category: 'Technology, Sales',
    abbreviation: 'SFA',
    related_terms: 'CRM, Automation, Software',
    notes: 'فناوریایی که وظایف عملیاتی تیم فروش را خودکار میکند.',
  },
  {
    word: 'Market Segmentation',
    english_definition:
      'The process of dividing a broad consumer or business market into sub-groups based on shared characteristics.',
    persian_meaning: 'تقسیم‌بندی بازار',
    example:
      'Our market segmentation focuses on small businesses in the tech industry.',
    category: 'Marketing, Strategy',
    related_terms: 'Target Audience, Demographics, Niche',
    notes: 'طبقه‌بندی مشتریان بالقوه به گروه‌های کوچکتر با نیازهای مشابه.',
  },
  {
    word: 'Closing Techniques',
    english_definition:
      'Specific methods or phrases used by salespeople to secure a commitment or finalize a sale.',
    persian_meaning: 'تکنیک‌های بستن قرارداد / نهایی‌سازی فروش',
    example: 'The "assumptive close" is a popular closing technique.',
    category: 'Sales, Skills',
    related_terms: 'Finalization, Commitment, Deal Closure',
    notes: 'روش‌های متقاعد کردن مشتری برای گرفتن تصمیم نهایی خرید.',
  },
  {
    word: 'Referral',
    english_definition:
      'A recommendation from an existing customer to a potential new customer.',
    persian_meaning: 'معرفی / پیشنهاد از طریق مشتری فعلی',
    example: 'We offer incentives to customers who provide successful referrals.',
    category: 'Sales, Marketing, CRM',
    related_terms: 'Recommendation, Word-of-Mouth, Lead Source',
    notes: 'یکی از مؤثرترین و کم‌هزینه‌ترین روش‌های جذب مشتری جدید.',
  },
  {
    word: 'Competitive Analysis',
    english_definition:
      'The assessment of the strengths and weaknesses of current and potential competitors.',
    persian_meaning: 'تحلیل رقبا',
    example:
      'A thorough competitive analysis helps us position our product more effectively.',
    category: 'Strategy, Marketing',
    related_terms: 'Benchmarking, Market Research, Competitors',
    notes: 'بررسی و ارزیابی محصولات، استراتژی‌ها و نقاط قوت و ضعف رقبا.',
  },
  {
    word: 'After-Sales Service',
    english_definition:
      'Support and service provided to a customer after they have purchased a product or service.',
    persian_meaning: 'خدمات پس از فروش',
    example:
      'Excellent after-sales service is crucial for building customer loyalty.',
    category: 'CRM, Sales, Customer Service',
    related_terms: 'Support, Warranty, Maintenance',
    notes: 'کلیه خدماتی که پس از تکمیل فروش برای رضایت و حفظ مشتری ارائه می‌شود.',
  },
  {
    word: 'Whitespace Analysis',
    english_definition:
      'Identifying unmet needs or sales opportunities within an existing customer account (e.g., selling additional products).',
    persian_meaning: 'تحلیل فضای خالی / فرصت‌های توسعه درون مشتری',
    example:
      'Whitespace analysis revealed we could sell our analytics module to 60% of our current clients.',
    category: 'Sales, CRM, Strategy',
    related_terms: 'Account Development, Up-selling, Opportunity',
    notes: 'کشف فرصت‌های فروش بیشتر به مشتریان فعلی.',
  },
  {
    word: 'MQO / MQL / SQL',
    english_definition:
      'Stages of lead qualification. MQL: A lead deemed more likely to become a customer based on marketing engagement. SQL: A lead that sales has accepted as a viable opportunity.',
    persian_meaning: 'سرنخ واجد شرایط بازاریابی / سرنخ واجد شرایط فروش',
    example:
      'Once a lead becomes an SQL, it is assigned to a sales rep.',
    category: 'Marketing, Sales, CRM',
    abbreviation: 'MQO (Marketing Qualified Opportunity) / MQL (Marketing Qualified Lead) / SQL (Sales Qualified Lead)',
    related_terms: 'Lead Qualification, Funnel, Handoff',
    notes:
      'معیارها و مراحل ارزیابی و تحویل سرنخ‌ها از بازاریابی به فروش.',
  },
  {
    word: 'Activity Management',
    english_definition:
      'The tracking and planning of sales-related activities such as calls, meetings, emails, and tasks.',
    persian_meaning: 'مدیریت فعالیت‌ها',
    example:
      'Good activity management ensures consistent customer outreach.',
    category: 'Sales, CRM, Management',
    related_terms: 'Task Tracking, Productivity, CRM',
    notes: 'نظارت بر اقدامات روزانه فروشندگان برای اطمینان از بهره‌وری.',
  },
  {
    word: 'Contact Management',
    english_definition:
      'The process of storing, organizing, and tracking information about current and potential contacts.',
    persian_meaning: 'مدیریت مخاطبین',
    example:
      'Contact management is a fundamental feature of any CRM system.',
    category: 'CRM, Sales',
    related_terms: 'Database, Address Book, CRM',
    notes: 'نگهداری و سازماندهی اطلاعات تمام افراد و شرکت‌های مرتبط.',
  },
  {
    word: 'Prospecting',
    english_definition:
      'The first step in the sales process, involving identifying and contacting potential customers.',
    persian_meaning: 'جستجو و یافتن مشتری بالقوه',
    example: 'Prospecting takes up about 30% of a sales rep\'s time.',
    category: 'Sales, Process',
    related_terms: 'Lead Generation, Outreach, Cold Calling',
    notes:
      'مرحله شناسایی و تماس اولیه با افراد یا شرکت‌هایی که ممکن است به محصول نیاز داشته باشند.',
  },
  {
    word: 'Social Selling',
    english_definition:
      'The use of social media platforms to find, connect with, understand, and nurture sales prospects.',
    persian_meaning: 'فروش اجتماعی',
    example:
      'LinkedIn is a powerful tool for social selling in B2B industries.',
    category: 'Sales, Marketing, Digital',
    related_terms: 'Social Media, Networking, Engagement',
    notes: 'استفاده از شبکه‌های اجتماعی برای ساخت رابطه و ایجاد فرصت فروش.',
  },
  {
    word: 'Customer Success',
    english_definition:
      'A proactive approach to ensuring customers achieve their desired outcomes while using a product or service.',
    persian_meaning: 'موفقیت مشتری',
    example:
      'The customer success team works to onboard and train new clients.',
    category: 'CRM, Service',
    abbreviation: 'CS',
    related_terms: 'Retention, Onboarding, Advocacy',
    notes: 'فلسفه و فعالیت‌های متمرکز بر کمک به مشتری برای رسیدن به اهدافش.',
  },
  {
    word: 'Escalation Management',
    english_definition:
      'The process of handling customer complaints or issues that require higher-level attention or expertise.',
    persian_meaning: 'مدیریت ارجاع مسائل (اسکالیشن)',
    example:
      'A clear escalation management process ensures critical issues are resolved quickly.',
    category: 'CRM, Customer Service',
    related_terms: 'Complaint, Support, Resolution',
    notes: 'مسیر تعریف‌شده برای حل مسائل پیچیده یا فوری مشتری.',
  },
  {
    word: 'Benchmarking',
    english_definition:
      'Comparing one\'s business processes and performance metrics to industry bests or best practices from other companies.',
    persian_meaning: 'اندازه‌گیری مقایسه‌ای / بنچمارک',
    example:
      'Benchmarking our sales cycle length against industry leaders revealed areas for improvement.',
    category: 'Management, Metrics',
    related_terms: 'KPIs, Best Practices, Comparison',
    notes: 'فرآیند مقایسه عملکرد با معیارهای داخلی یا خارجی برای یافتن زمینه‌های پیشرفت.',
  },
  {
    word: 'Ethical Selling',
    english_definition:
      'A sales approach based on honesty, integrity, and prioritizing the customer\'s best interests to build long-term trust.',
    persian_meaning: 'فروش اخلاق‌مدار',
    example:
      'Ethical selling focuses on creating value, not just closing a deal at any cost.',
    category: 'Sales, Philosophy',
    related_terms: 'Integrity, Trust, Relationship Selling',
    notes: 'رویکردی در فروش که بر شفافیت، راستگویی و منافع متقابل تأکید دارد.',
  },
]

export default part2
